### ISSUE TITLE
Conda installation issue: tensorflow version missing in channel

### ISSUE THREAD

**Issue by nataquinones** [BolognaBiocomp/deepsig#41]
I was having problems installing deepsig with:
`conda install -c bioconda deepsig`

I believe the problem might be that bioconda does not have the right tensorflow version(?) I ended up installing it in a new environment (because it required python v.3.8.20) adding the anaconda channel as well:

`mamba create --name deepsig -c bioconda -c anaconda deepsig`

**Comment by MirkMart** [comment]
I had the same problem this morning. I overcame it installing 'python 3.8.20' without the need to create a new environment. I added also '-c anaconda' to the mamba installation command.

 ```
mamba install python=3.8.20
mamba install -c bioconda -c anaconda deepsig
```

**Comment by tseemann** [comment]
It would be better to not have to invoke Anaconda in light of its weird licencing issues.

Does the bioconda recipe just need to be changed?

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deepsig/meta.yaml
```
requirements:
  host:
    - python =3.8, <3.9
    - pip
  run:
    - python =3.8, <3.9
    - biopython >=1.78
    - numpy =1.23
    - keras =2.4.3
    - tensorflow =2.2.0
    ```
